version: "3"

services:
  vote:
    image: dockersamples/examplevotingapp_vote:before
    ports:
      - "5000:80"
    networks:
      - frontend-test
  redis:
    image: redis:3.2
    networks:
      - frontend-test
  worker:
    image: dockersamples/examplevotingapp_worker
    networks:
      - frontend-test
      - backend-test
  db:
    image: postgres:9.4
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
      - POSTGRES_DB=/var/lib/postgresql/data
    networks:
      - backend-test
  result:
    image: dockersamples/examplevotingapp_result:before
    networks:
      - backend-test
    ports:
      - "5001:80"

networks:
  frontend-test:
  backend-test:
