version: '3'

services:
  drupal:
    build: .
    ports:
      - '8080:80'
    depends_on:
      - postgres
  postgres:
    image: postgres:9.6
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=drupal-data:/var/lib/postgresql/data
